url: "https://annafranchi.me"
baseurl: ""
title: Anna Franchi
plugins:
  - jekyll-last-modified-at
markdown: kramdown
collections:
  sections:
    output: true
    sort_by: order
  crafts:
    output: true
